CREATE DATABASE IF NOT EXISTS recharge_db;
USE recharge_db;

CREATE TABLE IF NOT EXISTS tickets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type_carte VARCHAR(50) NOT NULL,
    montant DECIMAL(10,2) NOT NULL,
    code_ticket VARCHAR(100) NOT NULL,
    user_email VARCHAR(150),
    statut VARCHAR(20) DEFAULT 'EN_ATTENTE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;